spring:
  data:
    mongodb:
      database: auth
config:
  resetmongo: true
  user:
    superuser: vikas
    superuserpassword: root123
    superuseremail: adiwalv@gmail.com
  client:
    rootclient: server
    rootclientpassword: server123
    userclient: client
    userclientpassword: client123