spring:
  data:
    mongodb:
      database: security
config:
  resetmongo: true
  user:
    superuser: vikas
    superuserpassword: root123
  client:
    rootclient: server
    rootclientpassword: server123
    userclient: client
    userclientpassword: client123