spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: vikas
    password: root123
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true